name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - new-portfolio  # Se ejecuta solo cuando haces push a la rama new-portfolio

permissions:
  contents: write  # Permiso para escribir en el repositorio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --force

      - name: Build and export
        run: npm run build && npx next export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Sube la carpeta out a gh-pages
